---
driver:
  name: ec2
  require_chef_omnibus: 12.17.44
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['sg-97e55ef2']
  interface: private
  iam_profile_name: logstash
  subnet_id: subnet-a792da8f
  tags:
    Env: dev
    Type: test
    Operator: <%= ENV['USER'] %>

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  config_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
    driver:
      instance_type: c3.large
      tags:
        Name: logserver-default-ubuntu-1404
  - name: ubuntu-16.04
    driver:
      instance_type: i3.large
      image_id: ami-4e952658
      tags:
        Name: logserver-default-ubuntu-1404

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[aws::ec2_hints]
      - recipe[et_hostname]
      - recipe[et_logger]
      - recipe[log_data::default]
      - recipe[log_host_discovery::default]
      - recipe[logserver::default]
      - recipe[logserver_postop::start_elasticsearch]
      - role[es_master]
      - recipe[et_logger::forwarder]
    attributes:
      logserver:
        generate_cert: true
      filebeat:
        prospectors:
          syslog:
            filebeat:
              prospectors:
              - paths:
                - /var/log/auth.log
                - /var/log/syslog
                document_type: syslog
      et_logger:
        generate_cert: true
        skip_server_discovery: true
        ca_cert:
          self_signed:
            signing_key: /etc/logstash/lumberjack.key.pem
      et_elk:
        elasticsearch:
          custom_config:
            index.number_of_replicas: 0
      storage:
        ebs_volumes:
          vol1:
            device: /dev/xvde
            size: 2
            delete_on_termination: true
