---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  network:
  - - private_network
    - ip: '192.168.33.11'

provisioner:
  name: chef_zero
  config_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[log_data::default]
      - recipe[log_host_discovery::default]
      - recipe[logserver::default]
      - recipe[logserver_postop::start_elasticsearch]
      - role[es_master]
      - recipe[et_logger::forwarder]
    attributes:
      logserver:
        generate_cert: true
      filebeat:
        prospectors:
          syslog:
            filebeat:
              prospectors:
              - paths:
                - /var/log/auth.log
                - /var/log/syslog
                document_type: syslog
      et_logger:
        generate_cert: true
      et_logger:
        skip_server_discovery: true
        ca_cert:
          self_signed:
            signing_key: /etc/logstash/lumberjack.key.pem
      et_elk:
        elasticsearch:
          custom_config:
            index.number_of_replicas: 0
