---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  network:
  - - private_network
    - ip: '192.168.33.11'

provisioner:
  name: chef_zero
  config_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[log_data::default]
      - recipe[log_host_discovery::default]
      - recipe[logserver::default]
      - role[es_master]
      - recipe[elk_forwarder::default]
    attributes:
      logserver:
        generate_cert: true
      elk_forwarder:
        config:
          files:
            syslog:
              paths:
              - /var/log/auth.log
              - /var/log/syslog
              fields:
                type: syslog
        generate_cert: true
        ca_cert:
          self_signed:
            signing_key: /etc/logstash/lumberjack.key.pem
      et_elk:
        elasticsearch:
          custom_config:
            index.number_of_replicas: 0
