---
driver:
  name: ec2
  require_chef_omnibus: true
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.2xlarge
  interface: public
  tags:
    Name: logserver-ubuntu-1404
    Type: test

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environments: dev

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-9883c6f2
      tags:
        Env: public

suites:
  - name: default
    run_list:
      - recipe[log_data::default]
      - recipe[log_host_discovery::default]
      - recipe[logserver::default]
      - role[es_master]
      - recipe[elk_forwarder::default]
    attributes:
      logserver:
        generate_cert: true
      elk_forwarder:
        config:
          files:
            syslog:
              paths:
              - /var/log/auth.log
              - /var/log/syslog
              fields:
                type: syslog
        generate_cert: true
        ca_cert:
          self_signed:
            signing_key: /etc/logstash/lumberjack.key.pem
      et_elk:
        elasticsearch:
          custom_config:
            index.number_of_replicas: 0
