---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero
  config_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[log_data::default]
      - recipe[logserver::default]
      - role[es_master]
      - recipe[et_logger::forwarder]
    attributes:
      logserver:
        generate_cert: true
      elk_forwarder:
        generate_cert: true
        ca_cert:
          self_signed:
            signing_key: /etc/logstash/lumberjack.key.pem
      elasticsearch:
        custom_config:
          index.number_of_replicas: 0
