---
driver:
  name: ec2
  require_chef_omnibus: true
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  username: ubuntu
  flavor_id: c3.large
  interface: public

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  data_bags_path: <%= ENV['CHEF_REPO'] %>/data_bags
  environments_path: <%= ENV['CHEF_REPO'] %>/environments
  client_rb:
    environment: _default

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 4608

suites:
- name: default
  run_list:
    - recipe[logserver]
    # - role[loghost]
  attributes:
    # nginx:
    #   port: 8123
